notifications:
  email:
    on_success: [change] # default: change
    on_failure: [change] # default: always

sudo: required

language: php

php:
  - 5.5.9

services:
  - mysql

addons:
  hosts:
    - mellivora

before_script:
# Environment setup
  - bash tests/ci/setup_environment

# Mellivora setup and configuration
  - bash tests/ci/setup_mellivora

script:
  - bash tests/run_tests --debug